import fs from "node:fs/promises";
import path from "node:path";
import { config } from "../config.js";
import { llmClient } from "./client.js";
import { TriageResponseSchema } from "../schemas/triageSchema.js";
import { logCallMetrics } from "./costLogger.js";

const PROMPT_VERSION = "v1";

/**
 * Loads the versioned markdown prompt file.
 */
let cachedPrompt = null;
async function loadPromptSpec() {
  if (cachedPrompt) return cachedPrompt;
  const promptPath = path.join(config.promptsDir, `job-triage-${PROMPT_VERSION}.md`);
  cachedPrompt = await fs.readFile(promptPath, "utf-8");
  return cachedPrompt;
}

/**
 * Strips code fences and preamble from LLM text.
 */
function cleanModelOutput(rawText) {
  if (!rawText || typeof rawText !== "string") return "";
  let cleaned = rawText.trim();
  // Strip ```json ... ``` code blocks
  if (cleaned.startsWith("```")) {
    cleaned = cleaned.replace(/^```(?:json)?\s*/i, "").replace(/```$/, "").trim();
  }
  // Remove common leading conversational phrases if present
  const firstBrace = cleaned.indexOf("{");
  const lastBrace = cleaned.lastIndexOf("}");
  if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
    cleaned = cleaned.substring(firstBrace, lastBrace + 1);
  }
  return cleaned;
}

/**
 * Custom Error classes with HTTP status codes.
 */
export class LLMTimeoutError extends Error {
  constructor(message) {
    super(message);
    this.status = 504;
    this.name = "LLMTimeoutError";
  }
}

export class LLMValidationError extends Error {
  constructor(message, details = null) {
    super(message);
    this.status = 422;
    this.name = "LLMValidationError";
    this.details = details;
  }
}

export class LLMUnavailableError extends Error {
  constructor(message) {
    super(message);
    this.status = 503;
    this.name = "LLMUnavailableError";
  }
}

/**
 * Logs fatal unrecoverable model outputs to logs/quarantine.jsonl.
 */
async function quarantineFailedOutput(inputData, errorMsg, rawOutput) {
  try {
    await fs.mkdir(config.logsDir, { recursive: true });
    const quarantinePath = path.join(config.logsDir, "quarantine.jsonl");
    const entry = {
      timestamp: new Date().toISOString(),
      prompt_version: PROMPT_VERSION,
      input: inputData,
      error: errorMsg,
      raw_output: rawOutput
    };
    await fs.appendFile(quarantinePath, JSON.stringify(entry) + "\n", "utf-8");
  } catch (err) {
    // Non-fatal logging error
  }
}

/**
 * Deterministic fallback returned when kill switch (LLM_ENABLED=false) is active.
 */
function getDeterministicFallback(inputData) {
  const title = (inputData.title || "").toLowerCase();
  let domain = "other";
  if (title.includes("backend")) domain = "backend";
  else if (title.includes("frontend")) domain = "frontend";
  else if (title.includes("full") || title.includes("stack")) domain = "fullstack";
  else if (title.includes("devops") || title.includes("cloud")) domain = "devops_cloud";
  else if (title.includes("data") || title.includes("ai")) domain = "data_ai";

  let seniority = "unspecified";
  if (title.includes("senior")) seniority = "senior";
  else if (title.includes("lead")) seniority = "lead";
  else if (title.includes("junior")) seniority = "junior";
  else if (title.includes("staff") || title.includes("principal")) seniority = "senior";

  return {
    seniority,
    domain,
    workplace_type: "unspecified",
    visa_sponsorship: "unspecified",
    tech_stack: [],
    confidence: 0.5,
    one_sentence_summary: `Software engineering role: ${inputData.title} at ${inputData.company || "company"}.`,
    reason: "Deterministic fallback rule generated by emergency kill-switch policy."
  };
}

/**
 * Deterministic stub mock returned when LLM_STUB=1.
 */
function getStubResponse(inputData) {
  const fallback = getDeterministicFallback(inputData);
  fallback.reason = "Deterministic response generated in stub mode (LLM_STUB=1).";
  fallback.confidence = 0.95;
  fallback.tech_stack = ["Node.js", "Docker", "PostgreSQL"];
  fallback.workplace_type = "fully_remote";
  return fallback;
}

/**
 * Executes a call with exponential backoff & jitter for 429 and 5xx.
 * Never retries 400, 401, or 403.
 */
async function callModelWithRetries(messages, maxAttempts = 3) {
  let attempt = 0;
  let delay = 1000;

  while (attempt < maxAttempts) {
    attempt++;
    const startTime = Date.now();
    try {
      const response = await llmClient.chat.completions.create({
        model: config.llmModel,
        messages,
        temperature: 0.1,
        max_tokens: 600
      });
      return { response, durationMs: Date.now() - startTime };
    } catch (err) {
      const durationMs = Date.now() - startTime;
      const status = err.status || (err.response ? err.response.status : null);

      // Timeout detection
      if (err.name === "AbortError" || err.message?.includes("timeout") || status === 504) {
        if (attempt >= maxAttempts) {
          throw new LLMTimeoutError(`LLM call timed out after ${config.llmTimeoutMs}ms`);
        }
      }

      // Fast-fail on authentication or bad requests: NEVER retry 400, 401, 403
      if (status === 400 || status === 401 || status === 403) {
        console.error(`[LLM_FATAL] Fast-fail on HTTP ${status} (No retries allowed): ${err.message}`);
        throw err;
      }

      // Retryable errors: 429 (rate limit) or 5xx (server error)
      const isRetryable = status === 429 || (status >= 500 && status < 600) || !status;
      if (!isRetryable || attempt >= maxAttempts) {
        throw err;
      }

      // Obey Retry-After header if provided
      let waitTime = delay + Math.floor(Math.random() * 500); // Backoff + Jitter
      if (err.headers && err.headers["retry-after"]) {
        const retryAfterVal = parseInt(err.headers["retry-after"], 10);
        if (!isNaN(retryAfterVal)) waitTime = retryAfterVal * 1000;
      }

      console.warn(`[LLM_RETRY] Attempt ${attempt} failed with status ${status}. Retrying in ${waitTime}ms...`);
      await new Promise((r) => setTimeout(r, waitTime));
      delay *= 2;
    }
  }
}

/**
 * Main Triage Service function with 1x Repair Retry Loop and Quarantine Logging.
 */
export async function triageJob(jobInput, options = {}) {
  const startTime = Date.now();

  // 1. Check Kill Switch (Stage 4)
  if (!config.llmEnabled && !options.force) {
    console.log("[KILL_SWITCH] LLM is disabled (LLM_ENABLED=false). Returning deterministic fallback.");
    return {
      result: getDeterministicFallback(jobInput),
      metrics: { durationMs: Date.now() - startTime, isStub: true, neededRepair: false }
    };
  }

  // 2. Check Stub Mode (Stage 1)
  const isStub = config.llmStub || options.stub;
  if (isStub) {
    const stubResult = getStubResponse(jobInput);
    const durationMs = Date.now() - startTime;
    const metrics = await logCallMetrics({
      promptVersion: PROMPT_VERSION,
      model: "stub",
      inputTokens: 0,
      outputTokens: 0,
      durationMs,
      neededRepair: false,
      isStub: true
    });
    return { result: stubResult, metrics };
  }

  // 3. Prepare Prompt & Defensive Message Structure (Stage 2)
  const systemPrompt = await loadPromptSpec();
  const userPayloadString = JSON.stringify({
    title: jobInput.title,
    company: jobInput.company || "Not Specified",
    description: jobInput.description
  });

  const messages = [
    { role: "system", content: systemPrompt },
    { role: "user", content: `Please evaluate this tech job posting:\n${userPayloadString}` }
  ];

  // 4. Attempt 1: Call Model
  let neededRepair = false;
  let rawOutput = "";
  let usage = { prompt_tokens: 0, completion_tokens: 0 };
  let durationMs = 0;

  try {
    const callResult = await callModelWithRetries(messages);
    durationMs = callResult.durationMs;
    const message = callResult.response.choices[0]?.message;
    rawOutput = message?.content || "";
    usage = callResult.response.usage || usage;
  } catch (err) {
    if (err instanceof LLMTimeoutError) throw err;
    throw new LLMUnavailableError(`LLM provider communication failed: ${err.message}`);
  }

  // 5. Parse & Validate Attempt 1 (Stage 3)
  let parsedObject = null;
  let validationError = null;

  try {
    const cleaned = cleanModelOutput(rawOutput);
    parsedObject = JSON.parse(cleaned);
    const validationResult = TriageResponseSchema.safeParse(parsedObject);
    if (validationResult.success) {
      const metrics = await logCallMetrics({
        promptVersion: PROMPT_VERSION,
        model: config.llmModel,
        inputTokens: usage.prompt_tokens,
        outputTokens: usage.completion_tokens,
        durationMs,
        neededRepair: false
      });
      return { result: validationResult.data, metrics };
    } else {
      validationError = validationResult.error.message;
    }
  } catch (parseErr) {
    validationError = `JSON parse failed: ${parseErr.message}`;
  }

  // 6. Repair Retry (Exactly 1 Retry with Feedback)
  console.warn(`[REPAIR_RETRY] Model output rejected: ${validationError}. Initiating 1x repair retry...`);
  neededRepair = true;

  const repairMessages = [
    ...messages,
    { role: "assistant", content: rawOutput },
    {
      role: "user",
      content: `Your previous answer was rejected for this reason:\n${validationError}\n\nReturn ONLY a valid, corrected JSON object matching the exact schema without any markdown code blocks or conversational text.`
    }
  ];

  try {
    const repairCall = await callModelWithRetries(repairMessages);
    durationMs += repairCall.durationMs;
    const repairRaw = repairCall.response.choices[0]?.message?.content || "";
    usage.prompt_tokens += repairCall.response.usage?.prompt_tokens || 0;
    usage.completion_tokens += repairCall.response.usage?.completion_tokens || 0;

    const cleanedRepair = cleanModelOutput(repairRaw);
    const repairedParsed = JSON.parse(cleanedRepair);
    const repairedValidation = TriageResponseSchema.safeParse(repairedParsed);

    if (repairedValidation.success) {
      console.log("[REPAIR_SUCCESS] Model successfully repaired its output on retry!");
      const metrics = await logCallMetrics({
        promptVersion: PROMPT_VERSION,
        model: config.llmModel,
        inputTokens: usage.prompt_tokens,
        outputTokens: usage.completion_tokens,
        durationMs,
        neededRepair: true
      });
      return { result: repairedValidation.data, metrics };
    }

    // Repair failed schema validation
    await quarantineFailedOutput(jobInput, repairedValidation.error.message, repairRaw);
    throw new LLMValidationError("Repaired model output failed schema validation", repairedValidation.error.format());
  } catch (finalErr) {
    if (finalErr instanceof LLMValidationError) throw finalErr;
    await quarantineFailedOutput(jobInput, finalErr.message, rawOutput);
    throw new LLMValidationError(`Repair failed to produce valid JSON: ${finalErr.message}`);
  }
}
